version: '3.8'

services:
  db:
    image: mysql:8.0    
    container_name: products_database
    env_file: 
      - ./server/.env
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql       
    networks:
      - products-network      
    
  products-api:
    container_name: products-api
    build: 
      context: ./server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "7777:7777"
    env_file:
      - ./server/.env
    command: npm run start:debug
    networks:
      - products-network

  products-web:
    container_name: products-web
    build: 
      context: ./web
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "8080:80"
    env_file:
      - ./web/.env
    # command: npm run dev --host
    networks:
      - products-network

volumes:
  db_data:
    driver: local

networks:
  products-network:
    name: products-network
    driver: bridge

