version: '3.8'

services:
  db:
    image: mysql:8.0    
    container_name: products_database
    env_file: 
      - ./server/.env
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql             

volumes:
  db_data:
    driver: local